### ISSUE TITLE
Fixed subnet networking snippet

### ISSUE THREAD

**Issue by blackandred** [riotkit-org/harbor-snippet-cooperative#1]
**Example:**

```yaml
version: "2.3"

networks:
  default:
    driver: bridge
    ipam:
     config:
       - subnet: 172.19.0.0/16
         gateway: 172.19.0.1
```
